version: '3'
services:
  web:
    build: ./
    volumes:
      - ./app:/app
    ports:
      - "8080:8080"
      - "5678:5678"
    environment:
      - HOST=0.0.0.0
      - PORT=8080
      - LOG_LEVEL=warning
